name: Add paper

on:
  workflow_dispatch:
    inputs:
      title:
        description: paper title
        required: true
      filename:
        description: filename
        required: true
      labels:
        description: labels
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
      - name: Create new file
        shell: bash
        env:
          title: ${{ inputs.title}}
          filename: ${{ inputs.filename}}
          labels: ${{ inputs.labels}}
        run: |
          cd papers/
          echo 'title: $title \nlabels: [$labels]' >> $filename.yml
          cd ..
      - name: Fetch 
        shell: bash
        run: |
          node scrips/updateData.mjs
          
